<a href="https://colab.research.google.com/github/Anuubhavvvv/python-basics/blob/main/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
arr=np.arange(0,10,step=1)

In [ ]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr[3:]=100

In [ ]:
print(arr)

[  0   1   2 100 100 100 100 100 100 100]


In [ ]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [ ]:
a=1.

In [ ]:
print(type(a))

<class 'float'>


In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

In [ ]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.random.rand(3,4)

array([[0.74836137, 0.50220532, 0.74369925, 0.91116793],
       [0.83678045, 0.73088684, 0.14861436, 0.14614336],
       [0.42425597, 0.54885441, 0.96076732, 0.41711995]])

In [ ]:
np.random.randint(1,19,4)

array([17, 13,  3, 11])

In [ ]:
import pandas as pd

In [ ]:
data=pd.read_csv("/content/sample_data/california_housing_test.csv")

In [ ]:
data.head(10)

longitude  latitude  ...  median_income  median_house_value
0    -122.05     37.37  ...         6.6085            344700.0
1    -118.30     34.26  ...         3.5990            176500.0
2    -117.81     33.78  ...         5.7934            270500.0
3    -118.36     33.82  ...         6.1359            330000.0
4    -119.67     36.33  ...         2.9375             81700.0
5    -119.56     36.51  ...         1.6635             67000.0
6    -121.43     38.63  ...         1.6641             67000.0
7    -120.65     35.48  ...         3.2250            166900.0
8    -122.84     38.40  ...         3.6696            194400.0
9    -118.02     34.08  ...         2.3333            164200.0

[10 rows x 9 columns]

In [ ]:
data.info

<bound method DataFrame.info of       longitude  latitude  ...  median_income  median_house_value
0       -122.05     37.37  ...         6.6085            344700.0
1       -118.30     34.26  ...         3.5990            176500.0
2       -117.81     33.78  ...         5.7934            270500.0
3       -118.36     33.82  ...         6.1359            330000.0
4       -119.67     36.33  ...         2.9375             81700.0
...         ...       ...  ...            ...                 ...
2995    -119.86     34.42  ...         1.1790            225000.0
2996    -118.14     34.06  ...         3.3906            237200.0
2997    -119.70     36.30  ...         2.2895             62000.0
2998    -117.12     34.10  ...         3.2708            162500.0
2999    -119.63     34.42  ...         8.5608            500001.0

[3000 rows x 9 columns]>

In [ ]:
data.describe

<bound method NDFrame.describe of       longitude  latitude  ...  median_income  median_house_value
0       -122.05     37.37  ...         6.6085            344700.0
1       -118.30     34.26  ...         3.5990            176500.0
2       -117.81     33.78  ...         5.7934            270500.0
3       -118.36     33.82  ...         6.1359            330000.0
4       -119.67     36.33  ...         2.9375             81700.0
...         ...       ...  ...            ...                 ...
2995    -119.86     34.42  ...         1.1790            225000.0
2996    -118.14     34.06  ...         3.3906            237200.0
2997    -119.70     36.30  ...         2.2895             62000.0
2998    -117.12     34.10  ...         3.2708            162500.0
2999    -119.63     34.42  ...         8.5608            500001.0

[3000 rows x 9 columns]>